"""
Standalone Strands Agent: returns_refunds_agent
Generated by AgentCore MCP Server

Integrations:
- Memory: Disabled
- Gateway: Disabled
- Knowledge Base: Enabled
"""

import os
import json
from strands import Agent, tool
from strands.models import BedrockModel
from strands_tools import retrieve
from strands_tools import current_time
from datetime import datetime

# Constants
MODEL_ID = "us.anthropic.claude-sonnet-4-5-20250929-v1:0"
REGION = "us-west-2"
SESSION_ID = "default-session"
ACTOR_ID = "default-actor"

# Model configuration
bedrock_model = BedrockModel(model_id=MODEL_ID, temperature=0.3)

# ============================================================================
# KNOWLEDGE BASE CONFIGURATION
# ============================================================================

# Load KB ID from config file
try:
    with open('kb_config.json', 'r') as f:
        kb_config = json.load(f)
        kb_id = kb_config.get('knowledge_base_id', '<PLACE-YOUR-KB-ID>')
except FileNotFoundError:
    kb_id = os.environ.get("KNOWLEDGE_BASE_ID", "<PLACE-YOUR-KB-ID>")

print(f"✓ Knowledge Base ID: {kb_id}")

# System prompt
system_prompt = f"""You are a helpful returns and refunds assistant. Help customers check return eligibility, calculate refunds, and understand policies. Use the retrieve tool to access Amazon return policy documents for accurate information. Be friendly and accurate.

When using the retrieve tool, always pass these parameters:
- knowledgeBaseId: {kb_id}
- region: {REGION}
- text: the search query"""

# Custom tool definitions
@tool

def check_return_eligibility(purchase_date: str, category: str) -> dict:
    """
    Check if an item is eligible for return.
    
    Args:
        purchase_date: Purchase date in YYYY-MM-DD format
        category: Product category (e.g., 'electronics', 'clothing', 'books')
    
    Returns:
        Dictionary with eligibility status and reason
    """
    try:
        purchase_dt = datetime.strptime(purchase_date, '%Y-%m-%d')
        days_since_purchase = (datetime.now() - purchase_dt).days
        
        # Return windows by category
        return_windows = {
            'electronics': 30,
            'clothing': 30,
            'books': 30,
            'jewelry': 30,
            'home': 30,
            'toys': 30,
            'default': 30
        }
        
        window = return_windows.get(category.lower(), return_windows['default'])
        
        if days_since_purchase < 0:
            return {
                'eligible': False,
                'reason': 'Purchase date is in the future',
                'days_remaining': 0
            }
        elif days_since_purchase <= window:
            return {
                'eligible': True,
                'reason': f'Within {window}-day return window',
                'days_remaining': window - days_since_purchase
            }
        else:
            return {
                'eligible': False,
                'reason': f'Exceeds {window}-day return window',
                'days_remaining': 0
            }
    except ValueError:
        return {
            'eligible': False,
            'reason': 'Invalid date format. Use YYYY-MM-DD',
            'days_remaining': 0
        }

@tool
def calculate_refund_amount(original_price: float, condition: str, return_reason: str) -> dict:
    """
    Calculate refund amount based on price, condition, and reason.
    
    Args:
        original_price: Original purchase price
        condition: Item condition ('new', 'opened', 'used', 'damaged')
        return_reason: Reason for return ('defective', 'wrong_item', 'changed_mind', 'not_as_described')
    
    Returns:
        Dictionary with refund details
    """
    if original_price < 0:
        return {
            'refund_amount': 0.0,
            'deduction': 0.0,
            'reason': 'Invalid price'
        }
    
    # Base refund is full price
    refund = original_price
    deduction = 0.0
    deduction_reason = []
    
    # Condition-based deductions
    condition_deductions = {
        'new': 0.0,
        'opened': 0.0,
        'used': 0.15,  # 15% restocking fee
        'damaged': 0.25  # 25% restocking fee
    }
    
    condition_lower = condition.lower()
    if condition_lower in condition_deductions:
        condition_deduction = condition_deductions[condition_lower]
        if condition_deduction > 0:
            deduction += original_price * condition_deduction
            deduction_reason.append(f'{int(condition_deduction * 100)}% restocking fee for {condition_lower} condition')
    
    # Return reason adjustments
    if return_reason.lower() in ['defective', 'wrong_item', 'not_as_described']:
        # Full refund for seller/product issues
        deduction = 0.0
        deduction_reason = ['Full refund - seller/product issue']
    
    refund_amount = original_price - deduction
    
    return {
        'refund_amount': round(refund_amount, 2),
        'deduction': round(deduction, 2),
        'reason': '; '.join(deduction_reason) if deduction_reason else 'Full refund'
    }

@tool
def format_policy_response(policy_text: str, customer_question: str = '') -> str:
    """
    Format policy information in a customer-friendly way.
    
    Args:
        policy_text: Raw policy text from knowledge base
        customer_question: Optional customer question for context
    
    Returns:
        Formatted, customer-friendly policy response
    """
    # Add friendly header
    formatted = '📋 Return Policy Information\n'
    formatted += '=' * 50 + '\n\n'
    
    if customer_question:
        formatted += f'Regarding your question: "{customer_question}"\n\n'
    
    # Clean up the policy text
    lines = policy_text.strip().split('\n')
    
    for line in lines:
        line = line.strip()
        if not line:
            formatted += '\n'
        elif line.isupper() or line.endswith(':'):
            # Treat as section header
            formatted += f'\n{line}\n'
            formatted += '-' * len(line) + '\n'
        elif line.startswith('-') or line.startswith('•'):
            # Already a bullet point
            formatted += f'  {line}\n'
        else:
            # Regular text
            formatted += f'{line}\n'
    
    formatted += '\n' + '=' * 50 + '\n'
    formatted += '💡 Tip: If you have more questions, just ask!\n'
    
    return formatted


def run_agent(user_input: str, session_id: str = SESSION_ID, actor_id: str = ACTOR_ID):
    """Run the agent with user input"""
    
    # Build tools list
    custom_tools = [retrieve, current_time, check_return_eligibility, calculate_refund_amount, format_policy_response]
    
    # Create agent
    agent = Agent(
        model=bedrock_model,
        tools=custom_tools,
        system_prompt=system_prompt
    )
    
    response = agent(user_input)
    return response.message["content"][0]["text"]

if __name__ == "__main__":
    # Example usage
    user_query = "Hello, how can you help me?"
    result = run_agent(user_query)
    print("\n" + "="*80)
    print("AGENT RESPONSE:")
    print("="*80)
    print(result)
