"""
Memory-Enabled Strands Agent: returns_agent_with_memory
Generated by AgentCore MCP Server

Integrations:
- Memory: Enabled (loads from memory_config.json)
- Gateway: Disabled
- Knowledge Base: Enabled (loads from kb_config.json)

Features:
- Remembers customer preferences across sessions
- Recalls previous return history
- Maintains conversation context
- All custom tools from original agent
"""

import os
import json
from strands import Agent, tool
from strands.models import BedrockModel
from strands_tools import retrieve
from strands_tools import current_time
from bedrock_agentcore.memory.integrations.strands.config import AgentCoreMemoryConfig, RetrievalConfig
from bedrock_agentcore.memory.integrations.strands.session_manager import AgentCoreMemorySessionManager
from datetime import datetime

# Constants
MODEL_ID = "us.anthropic.claude-sonnet-4-5-20250929-v1:0"
REGION = "us-west-2"
SESSION_ID = "default-session"
ACTOR_ID = "default-actor"

# Model configuration
bedrock_model = BedrockModel(model_id=MODEL_ID, temperature=0.3)

# ============================================================================
# LOAD CONFIGURATION FROM FILES
# ============================================================================

# Load Knowledge Base ID from config file
try:
    with open('kb_config.json', 'r') as f:
        kb_config = json.load(f)
        kb_id = kb_config.get('knowledge_base_id', '<PLACE-YOUR-KB-ID>')
except FileNotFoundError:
    kb_id = os.environ.get("KNOWLEDGE_BASE_ID", "<PLACE-YOUR-KB-ID>")

print(f"✓ Knowledge Base ID: {kb_id}")

# Load Memory ID from config file
try:
    with open('memory_config.json', 'r') as f:
        memory_config = json.load(f)
        memory_id = memory_config.get('memory_id', None)
        if memory_id:
            print(f"✓ Memory ID: {memory_id}")
        else:
            print("⚠️  Memory ID not found in config")
except FileNotFoundError:
    memory_id = os.environ.get("MEMORY_ID", None)
    if not memory_id:
        print("⚠️  memory_config.json not found and MEMORY_ID not set")

# ============================================================================
# MEMORY CONFIGURATION
# ============================================================================

def create_memory_session_manager(memory_id: str, session_id: str = SESSION_ID, actor_id: str = ACTOR_ID):
    """Create AgentCore Memory session manager with all three memory strategies"""
    agentcore_memory_config = AgentCoreMemoryConfig(
        memory_id=memory_id,
        session_id=session_id,
        actor_id=actor_id,
        retrieval_config={
            f"app/{actor_id}/semantic": RetrievalConfig(top_k=3),
            f"app/{actor_id}/preferences": RetrievalConfig(top_k=3),
            f"app/{actor_id}/{session_id}/summary": RetrievalConfig(top_k=2),
        }
    )
    
    return AgentCoreMemorySessionManager(
        agentcore_memory_config=agentcore_memory_config,
        region_name=REGION
    )

# System prompt
system_prompt = f"""You are a personalized returns assistant who remembers customer preferences and history. Use the retrieve tool to access Amazon return policy documents for accurate information.

When using the retrieve tool, always pass these parameters:
- knowledgeBaseId: {kb_id}
- region: {REGION}
- text: the search query

You have access to customer memory including:
- Previous conversations and return history
- Customer communication preferences
- Past interactions and context

Use this information to provide personalized, context-aware assistance."""

# ============================================================================
# CUSTOM TOOL DEFINITIONS (from original agent)
# ============================================================================

@tool
def check_return_eligibility(purchase_date: str, category: str) -> dict:
    """
    Check if an item is eligible for return.
    
    Args:
        purchase_date: Purchase date in YYYY-MM-DD format
        category: Product category (e.g., 'electronics', 'clothing', 'books')
    
    Returns:
        Dictionary with eligibility status and reason
    """
    try:
        purchase_dt = datetime.strptime(purchase_date, '%Y-%m-%d')
        days_since_purchase = (datetime.now() - purchase_dt).days
        return_windows = {
            'electronics': 30, 
            'clothing': 30, 
            'books': 30, 
            'jewelry': 30, 
            'home': 30, 
            'toys': 30, 
            'default': 30
        }
        window = return_windows.get(category.lower(), return_windows['default'])
        
        if days_since_purchase < 0:
            return {
                'eligible': False, 
                'reason': 'Purchase date is in the future', 
                'days_remaining': 0
            }
        elif days_since_purchase <= window:
            return {
                'eligible': True, 
                'reason': f'Within {window}-day return window', 
                'days_remaining': window - days_since_purchase
            }
        else:
            return {
                'eligible': False, 
                'reason': f'Exceeds {window}-day return window', 
                'days_remaining': 0
            }
    except ValueError:
        return {
            'eligible': False, 
            'reason': 'Invalid date format. Use YYYY-MM-DD', 
            'days_remaining': 0
        }

@tool
def calculate_refund_amount(original_price: float, condition: str, return_reason: str) -> dict:
    """
    Calculate refund amount based on price, condition, and reason.
    
    Args:
        original_price: Original purchase price
        condition: Item condition ('new', 'opened', 'used', 'damaged')
        return_reason: Reason for return ('defective', 'wrong_item', 'changed_mind', 'not_as_described')
    
    Returns:
        Dictionary with refund details
    """
    if original_price < 0:
        return {
            'refund_amount': 0.0, 
            'deduction': 0.0, 
            'reason': 'Invalid price'
        }
    
    refund = original_price
    deduction = 0.0
    deduction_reason = []
    condition_deductions = {
        'new': 0.0, 
        'opened': 0.0, 
        'used': 0.15,  # 15% restocking fee
        'damaged': 0.25  # 25% restocking fee
    }
    
    condition_lower = condition.lower()
    if condition_lower in condition_deductions:
        condition_deduction = condition_deductions[condition_lower]
        if condition_deduction > 0:
            deduction += original_price * condition_deduction
            deduction_reason.append(f'{int(condition_deduction * 100)}% restocking fee for {condition_lower} condition')
    
    if return_reason.lower() in ['defective', 'wrong_item', 'not_as_described']:
        deduction = 0.0
        deduction_reason = ['Full refund - seller/product issue']
    
    refund_amount = original_price - deduction
    return {
        'refund_amount': round(refund_amount, 2), 
        'deduction': round(deduction, 2), 
        'reason': '; '.join(deduction_reason) if deduction_reason else 'Full refund'
    }

@tool
def format_policy_response(policy_text: str, customer_question: str = '') -> str:
    """
    Format policy information in a customer-friendly way.
    
    Args:
        policy_text: Raw policy text from knowledge base
        customer_question: Optional customer question for context
    
    Returns:
        Formatted, customer-friendly policy response
    """
    formatted = '📋 Return Policy Information\n' + '=' * 50 + '\n\n'
    if customer_question:
        formatted += f'Regarding your question: "{customer_question}"\n\n'
    
    lines = policy_text.strip().split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            formatted += '\n'
        elif line.isupper() or line.endswith(':'):
            formatted += f'\n{line}\n' + '-' * len(line) + '\n'
        elif line.startswith('-') or line.startswith('•'):
            formatted += f'  {line}\n'
        else:
            formatted += f'{line}\n'
    
    formatted += '\n' + '=' * 50 + '\n'
    formatted += '💡 Tip: If you have more questions, just ask!\n'
    return formatted

# ============================================================================
# AGENT RUNNER
# ============================================================================

def run_agent(user_input: str, session_id: str = SESSION_ID, actor_id: str = ACTOR_ID):
    """Run the agent with user input and memory"""
    
    # Build tools list (all custom tools + built-in tools)
    custom_tools = [
        retrieve, 
        current_time, 
        check_return_eligibility, 
        calculate_refund_amount, 
        format_policy_response
    ]
    
    # Configure memory if available
    if not memory_id:
        print("⚠️  Running without memory - set MEMORY_ID or create memory_config.json")
        session_manager = None
    else:
        session_manager = create_memory_session_manager(memory_id, session_id, actor_id)
        print(f"✓ Memory session configured for actor: {actor_id}, session: {session_id}")
    
    # Create agent with memory
    agent = Agent(
        model=bedrock_model,
        tools=custom_tools,
        system_prompt=system_prompt,
        session_manager=session_manager
    )
    
    response = agent(user_input)
    return response.message["content"][0]["text"]

if __name__ == "__main__":
    print("\n" + "="*80)
    print("MEMORY-ENABLED RETURNS AGENT")
    print("="*80)
    print()
    
    # Example usage with user_001 (who has memory)
    print("Testing with user_001 (has memory)...")
    print()
    
    user_query = "Hi, I need help with a return. Can you remind me what my notification preferences are?"
    result = run_agent(user_query, session_id="test_session", actor_id="user_001")
    
    print("\n" + "="*80)
    print("AGENT RESPONSE:")
    print("="*80)
    print(result)
    print()
